### ISSUE TITLE
node crash when requesting RESTful API before initial checkpoint sync completes

### ISSUE THREAD

**Issue by junwei0117** [iotaledger/iota#4087]
## Bug description

Requesting any checkpoint related RESTful API (including health, node info, etc.) before the message `Finished syncing and executing checkpoint 0` appears in the log will cause the node to crash.

In our scenario, we start the indexer and the IOTA node in a single docker compose setup. The indexer repeatedly sends requests to the IOTA node endpoint `/checkpoints/0/full`, which results in the IOTA node crashing. 

Additionally, we use `/api/v1/health` to monitor the IOTA node docker container health status, but this also causes the IOTA node to crash.

## Errors

```
iota  | thread 'iota-node-runtime' panicked at crates/iota-rest-api/src/response.rs:133:74:
iota  | called `Result::unwrap()` on an `Err` value: Error { inner: Inner { kind: Missing, source: Some("unable to get latest checkpoint") } }
iota  | stack backtrace:
iota  | 2024-11-16T03:23:37.910765Z ERROR telemetry_subscribers: panicked at crates/iota-rest-api/src/response.rs:133:74:
iota  | called `Result::unwrap()` on an `Err` value: Error { inner: Inner { kind: Missing, source: Some("unable to get latest checkpoint") } } panic.file="crates/iota-rest-api/src/response.rs" panic.line=133 panic.column=74
iota  |    0: rust_begin_unwind
iota  |    1: core::panicking::panic_fmt
iota  |    2: core::result::unwrap_failed
iota  |    3: <axum::middleware::map_response::MapResponse<F,S,I,(T1,)> as tower_service::Service<http::request::Request<B>>>::call::{{closure}}
iota  |    4: <axum::middleware::map_response::ResponseFuture as core::future::future::Future>::poll
iota  |    5: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
iota  |    6: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
iota  |    7: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
iota  |    8: <tower::util::map_response::MapResponseFuture<F,N> as core::future::future::Future>::poll
iota  |    9: <tower::util::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
iota  |   10: <axum::routing::route::RouteFuture<E> as core::future::future::Future>::poll
iota  |   11: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
iota  |   12: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
iota  |   13: <tower::util::map_response::MapResponseFuture<F,N> as core::future::future::Future>::poll
iota  |   14: <tower::util::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
iota  |   15: <axum::routing::route::RouteFuture<E> as core::future::future::Future>::poll
iota  |   16: <tower::util::map_response::MapResponseFuture<F,N> as core::future::future::Future>::poll
iota  |   17: <axum::middleware::from_fn::FromFn<F,S,I,(T1,)> as tower_service::Service<http::request::Request<axum_core::body::Body>>>::call::{{closure}}
iota  |   18: <axum::middleware::from_fn::ResponseFuture as core::future::future::Future>::poll
iota  |   19: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
iota  |   20: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
iota  |   21: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
iota  |   22: <tower::util::map_response::MapResponseFuture<F,N> as core::future::future::Future>::poll
iota  |   23: <tower::util::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
iota  |   24: <axum::routing::route::RouteFuture<E> as core::future::future::Future>::poll
iota  |   25: <hyper_util::service::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
iota  |   26: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch
iota  |   27: <hyper::server::conn::http1::UpgradeableConnection<I,S> as core::future::future::Future>::poll
iota  |   28: <hyper_util::server::conn::auto::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll
iota  |   29: <axum::serve::Serve<M,S> as core::future::into_future::IntoFuture>::into_future::{{closure}}::{{closure}}
iota  |   30: tokio::runtime::task::core::Core<T,S>::poll
iota  |   31: tokio::runtime::task::harness::Harness<T,S>::poll
iota  |   32: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
iota  |   33: tokio::runtime::scheduler::multi_thread::worker::Context::run
iota  |   34: tokio::runtime::context::scoped::Scoped<T>::set
iota  |   35: tokio::runtime::context::runtime::enter_runtime
iota  |   36: tokio::runtime::scheduler::multi_thread::worker::run
iota  |   37: tokio::runtime::task::core::Core<T,S>::poll
iota  |   38: tokio::runtime::task::harness::Harness<T,S>::poll
iota  |   39: tokio::runtime::blocking::pool::Inner::run
iota  | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by kodemartin** [comment]
> IMO no matter what endpoint in an API is called, the node shouldn't panic.
> 
> [@kodemartin](https://github.com/kodemartin) who should tackle this one? We can have a look at this since our teams are both codeowners afaik if you are fine with that.

Of course @muXxer feel free to handle this.
