### ISSUE TITLE
IOTA node panic and failure to recover with multiple types of panics

### ISSUE THREAD

**Issue by junwei0117** [iotaledger/iota#4388]
## Bug description

At first, the node suddenly restarted without any error. After the restart, it encountered an `assertion failed` panic, and since then, it hasn’t been able to recover after the restart. I tried restoring the database from a RocksDB snapshot and also cleaned the consensus database, then the node can start working and commit messages to the consensus, after syncing and running for a while, it still randomly encounters either `assertion failed` panic or `Block Rejected` panic, and the node fails to recover again.

Even when the node is working, I noticed that its `last_sent_checkpoint_signature` is always 0, and I see the following message in the logs:

```
INFO iota_network::randomness: skipping sending partial sigs, we already have completed this round
```

## Version

v0.7.3-rc

## Errors

```
There are 239 pending unscored subdags in DagState.
2024-12-07 03:35:17.164	2024-12-06T19:35:17.164345Z  INFO consensus_core::leader_schedule: Using scoring strategy vote for ReputationScoreCalculator
2024-12-07 03:35:17.164	thread 'iota-node-runtime' panicked at consensus/core/src/commit_observer.rs:117:2024-12-06T19:35:17.164366Z ERROR telemetry_subscribers: panicked at consensus/core/src/commit_observer.rs:117:13:
2024-12-07 03:35:17.164	assertion failed: last_commit_index >= last_processed_commit_index panic.file="consensus/core/src/commit_observer.rs" panic.line=117 panic.column=13
2024-12-07 03:35:17.164	13:
2024-12-07 03:35:17.164	assertion failed: last_commit_index >= last_processed_commit_index
2024-12-07 03:35:17.164	stack backtrace:
2024-12-07 03:35:17.179	   0: rust_begin_unwind
2024-12-07 03:35:17.179	   1: core::panicking::panic_fmt
2024-12-07 03:35:17.180	   2: core::panicking::panic
2024-12-07 03:35:17.181	   3: consensus_core::commit_observer::CommitObserver::new
2024-12-07 03:35:17.181	   4: consensus_core::authority_node::AuthorityNode<N>::start::{{closure}}
2024-12-07 03:35:17.181	   5: <iota_core::consensus_manager::mysticeti_manager::MysticetiManager as iota_core::consensus_manager::ConsensusManagerTrait>::start::{{closure}}
2024-12-07 03:35:17.181	   6: <iota_core::consensus_manager::ConsensusManager as iota_core::consensus_manager::ConsensusManagerTrait>::start::{{closure}}
2024-12-07 03:35:17.181	   7: iota_node::IotaNode::start_epoch_specific_validator_components::{{closure}}
2024-12-07 03:35:17.181	   8: iota_node::IotaNode::construct_validator_components::{{closure}}
2024-12-07 03:35:17.181	   9: iota_node::IotaNode::start_async::{{closure}}
2024-12-07 03:35:17.182	  10: iota_node::main::{{closure}}
2024-12-07 03:35:17.182	  11: tokio::runtime::task::harness::Harness<T,S>::poll
2024-12-07 03:35:17.182	  12: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
2024-12-07 03:35:17.182	  13: tokio::runtime::scheduler::multi_thread::worker::Context::run
2024-12-07 03:35:17.182	  14: tokio::runtime::context::scoped::Scoped<T>::set
2024-12-07 03:35:17.182	  15: tokio::runtime::context::runtime::enter_runtime
2024-12-07 03:35:17.182	  16: tokio::runtime::scheduler::multi_thread::worker::run
2024-12-07 03:35:17.182	  17: tokio::runtime::task::core::Core<T,S>::poll
2024-12-07 03:35:17.182	  18: tokio::runtime::task::harness::Harness<T,S>::poll
2024-12-07 03:35:17.182	  19: tokio::runtime::blocking::pool::Inner::run
2024-12-07 03:35:17.183	note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
[Explore-logs-2024-12-07 03_49_10.txt](https://github.com/user-attachments/files/18043520/Explore-logs-2024-12-07.03_49_10.txt)

```
2024-12-07 05:08:52.598	Block Rejected! Attempted to add block B112463(M,M/PUKQHFj0uz3z3CE1PtfxdJ7IOCfS3GPj7GH1FM0qg=)(1733519186236ms;[B112462(M,NWtLDlQyUWodDAtXrKES7dVPpwU6EjYCs791yotDK8E=), B112461(A,2YobYY9bpeRW1uEs7JruXArm0YkZ/4RK4gUfGE4Uoeo=), B112462(B,Tx9UBD2QABtXSMJD04sfPVrINM7679k5JIXphYGFmGM=), B112462(D,RXt+VmYkPAl5nDgBIMZn+Bft4z8/f1L/nrzZBNE39xI=), B112462(E,sGl9Wm7PnyFdLVO7ZnLtQOi6we4M5QH9S4Qquv3aPaU=), B112462(F,BitXQpxncMK9SXk+wlCpk4bDhcBrkkVwZ1xGFS9KtJQ=), B112462(G,V1OGg3+jkfLMPkDeB9mJZUd3OrsrV3JKk/fyM6oFAGs=), B112461(I,a75if0vmmM1h4STIxTbbDPYxfKX0IS9dZFfA96VowDQ=), B112462(J,PbfqzCOmPDhNHzQuBIcjFfbxaqaFoO2G9fW/B23F2Rw=), B112462(K,R3zrYFJbWNydUzmMscnjykm5qwfs/vLstIAooot1h74=), B112462(L,yXkFjnmiscx/WY5l2Crjq/DuAIZzgqPpYL+EfeJ/faI=), B112462(N,HS61Up2gy1Ra/40lYmSKVKYtJgmzL8jo5dqtq6TfXn4=), B112462(P,QA7/laQZ9HBtK1nqWnE82xqpS5nLxERtU0yAePhso9A=), B112462(Q,LSVUPQSygy0MZ+oGyb/rIPLxhzOlUmXCb+PoscX8TyI=), B112461(R,CN9KnY3rF+py2whoMWLmhr2pNMoCUggk4oAN6dn42U0=), B112462(S,vCcNSdSByfRXafD595rilGpx/zltE8ccQmsCDSetMSo=), B112461(T,duS26KNw10M2JSkHi/rQ0QsK4gQJ0eEIs8tQwHQq6RQ=)];0t;1c) to own slot where block(s) [
2024-12-07 05:08:52.598	    B112463(M,DGGijwfbM3Pe376RNbztHqvhaUm1qUDa8I194TACyFk=)(1733519305610ms;[B112462(M,NWtLDlQyUWodDAtXrKES7dVPpwU6EjYCs791yotDK8E=), B112461(A,2YobYY9bpeRW1uEs7JruXArm0YkZ/4RK4gUfGE4Uoeo=), B112462(B,Tx9UBD2QABtXSMJD04sfPVrINM7679k5JIXphYGFmGM=), B0(C,KVzAXjBxFtmeYXj/KWcrlnbIsX0H57U4MJICqcpUYm8=), B112462(D,RXt+VmYkPAl5nDgBIMZn+Bft4z8/f1L/nrzZBNE39xI=), B112462(E,sGl9Wm7PnyFdLVO7ZnLtQOi6we4M5QH9S4Qquv3aPaU=), B112462(F,BitXQpxncMK9SXk+wlCpk4bDhcBrkkVwZ1xGFS9KtJQ=), B112462(G,V1OGg3+jkfLMPkDeB9mJZUd3OrsrV3JKk/fyM6oFAGs=), B0(H,OBTX8wOtJARWqJ6nfZ+swV0PxD5wINU6XUoOsHPd/VI=), B112461(I,a75if0vmmM1h4STIxTbbDPYxfKX0IS9dZFfA96VowDQ=), B112462(J,PbfqzCOmPDhNHzQuBIcjFfbxaqaFoO2G9fW/B23F2Rw=), B112462(K,R3zrYFJbWNydUzmMscnjykm5qwfs/vLstIAooot1h74=), B112462(L,yXkFjnmiscx/WY5l2Crjq/DuAIZzgqPpYL+EfeJ/faI=), B112462(N,HS61Up2gy1Ra/40lYmSKVKYtJgmzL8jo5dqtq6TfXn4=), B112462(P,QA7/laQZ9HBtK1nqWnE82xqpS5nLxERtU0yAePhso9A=), B112462(Q,LSVUPQSygy0MZ+oGyb/rIPLxhzOlUmXCb+PoscX8TyI=), B112461(R,CN9KnY3rF+py2whoMWLmhr2pNMoCUggk4oAN6dn42U0=), B112462(S,vCcNSdSByfRXafD595rilGpx/zltE8ccQmsCDSetMSo=), B112461(T,duS26KNw10M2JSkHi/rQ0QsK4gQJ0eEIs8tQwHQq6RQ=)];1t;0c),
2024-12-07 05:08:52.598	] already exists. panic.file="consensus/core/src/dag_state.rs" panic.line=205 panic.column=13
2024-12-07 05:08:52.598	thread 'iota-node-runtime' panicked at consensus/core/src/dag_state.rs:205:13:
2024-12-07 05:08:52.598	Block Rejected! Attempted to add block B112463(M,M/PUKQHFj0uz3z3CE1PtfxdJ7IOCfS3GPj7GH1FM0qg=)(1733519186236ms;[B112462(M,NWtLDlQyUWodDAtXrKES7dVPpwU6EjYCs791yotDK8E=), B112461(A,2YobYY9bpeRW1uEs7JruXArm0YkZ/4RK4gUfGE4Uoeo=), B112462(B,Tx9UBD2QABtXSMJD04sfPVrINM7679k5JIXphYGFmGM=), B112462(D,RXt+VmYkPAl5nDgBIMZn+Bft4z8/f1L/nrzZBNE39xI=), B112462(E,sGl9Wm7PnyFdLVO7ZnLtQOi6we4M5QH9S4Qquv3aPaU=), B112462(F,BitXQpxncMK9SXk+wlCpk4bDhcBrkkVwZ1xGFS9KtJQ=), B112462(G,V1OGg3+jkfLMPkDeB9mJZUd3OrsrV3JKk/fyM6oFAGs=), B112461(I,a75if0vmmM1h4STIxTbbDPYxfKX0IS9dZFfA96VowDQ=), B112462(J,PbfqzCOmPDhNHzQuBIcjFfbxaqaFoO2G9fW/B23F2Rw=), B112462(K,R3zrYFJbWNydUzmMscnjykm5qwfs/vLstIAooot1h74=), B112462(L,yXkFjnmiscx/WY5l2Crjq/DuAIZzgqPpYL+EfeJ/faI=), B112462(N,HS61Up2gy1Ra/40lYmSKVKYtJgmzL8jo5dqtq6TfXn4=), B112462(P,QA7/laQZ9HBtK1nqWnE82xqpS5nLxERtU0yAePhso9A=), B112462(Q,LSVUPQSygy0MZ+oGyb/rIPLxhzOlUmXCb+PoscX8TyI=), B112461(R,CN9KnY3rF+py2whoMWLmhr2pNMoCUggk4oAN6dn42U0=), B112462(S,vCcNSdSByfRXafD595rilGpx/zltE8ccQmsCDSetMSo=), B112461(T,duS26KNw10M2JSkHi/rQ0QsK4gQJ0eEIs8tQwHQq6RQ=)];0t;1c) to own slot where block(s) [
2024-12-07 05:08:52.598	    B112463(M,DGGijwfbM3Pe376RNbztHqvhaUm1qUDa8I194TACyFk=)(1733519305610ms;[B112462(M,NWtLDlQyUWodDAtXrKES7dVPpwU6EjYCs791yotDK8E=), B112461(A,2YobYY9bpeRW1uEs7JruXArm0YkZ/4RK4gUfGE4Uoeo=), B112462(B,Tx9UBD2QABtXSMJD04sfPVrINM7679k5JIXphYGFmGM=), B0(C,KVzAXjBxFtmeYXj/KWcrlnbIsX0H57U4MJICqcpUYm8=), B112462(D,RXt+VmYkPAl5nDgBIMZn+Bft4z8/f1L/nrzZBNE39xI=), B112462(E,sGl9Wm7PnyFdLVO7ZnLtQOi6we4M5QH9S4Qquv3aPaU=), B112462(F,BitXQpxncMK9SXk+wlCpk4bDhcBrkkVwZ1xGFS9KtJQ=), B112462(G,V1OGg3+jkfLMPkDeB9mJZUd3OrsrV3JKk/fyM6oFAGs=), B0(H,OBTX8wOtJARWqJ6nfZ+swV0PxD5wINU6XUoOsHPd/VI=), B112461(I,a75if0vmmM1h4STIxTbbDPYxfKX0IS9dZFfA96VowDQ=), B112462(J,PbfqzCOmPDhNHzQuBIcjFfbxaqaFoO2G9fW/B23F2Rw=), B112462(K,R3zrYFJbWNydUzmMscnjykm5qwfs/vLstIAooot1h74=), B112462(L,yXkFjnmiscx/WY5l2Crjq/DuAIZzgqPpYL+EfeJ/faI=), B112462(N,HS61Up2gy1Ra/40lYmSKVKYtJgmzL8jo5dqtq6TfXn4=), B112462(P,QA7/laQZ9HBtK1nqWnE82xqpS5nLxERtU0yAePhso9A=), B112462(Q,LSVUPQSygy0MZ+oGyb/rIPLxhzOlUmXCb+PoscX8TyI=), B112461(R,CN9KnY3rF+py2whoMWLmhr2pNMoCUggk4oAN6dn42U0=), B112462(S,vCcNSdSByfRXafD595rilGpx/zltE8ccQmsCDSetMSo=), B112461(T,duS26KNw10M2JSkHi/rQ0QsK4gQJ0eEIs8tQwHQq6RQ=)];1t;0c),
2024-12-07 05:08:52.598	] already exists.
2024-12-07 05:08:52.598	stack backtrace:
2024-12-07 05:08:52.614	   0: rust_begin_unwind
2024-12-07 05:08:52.614	   1: core::panicking::panic_fmt
2024-12-07 05:08:52.614	   2: consensus_core::block_manager::BlockManager::try_accept_blocks
2024-12-07 05:08:52.614	   3: consensus_core::core::Core::add_blocks
2024-12-07 05:08:52.614	   4: consensus_core::core_thread::ChannelCoreThreadDispatcher::start::{{closure}}
2024-12-07 05:08:52.614	   5: tokio::runtime::task::core::Core<T,S>::poll
2024-12-07 05:08:52.615	   6: tokio::runtime::task::raw::poll
2024-12-07 05:08:52.615	   7: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
2024-12-07 05:08:52.615	   8: tokio::runtime::scheduler::multi_thread::worker::Context::run
2024-12-07 05:08:52.615	   9: tokio::runtime::context::scoped::Scoped<T>::set
2024-12-07 05:08:52.615	  10: tokio::runtime::context::runtime::enter_runtime
2024-12-07 05:08:52.615	  11: tokio::runtime::scheduler::multi_thread::worker::run
2024-12-07 05:08:52.615	  12: tokio::runtime::task::core::Core<T,S>::poll
2024-12-07 05:08:52.616	  13: tokio::runtime::task::harness::Harness<T,S>::poll
2024-12-07 05:08:52.616	  14: tokio::runtime::blocking::pool::Inner::run
2024-12-07 05:08:52.616	note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
[Explore-logs-2024-12-07 05_11_36.txt](https://github.com/user-attachments/files/18043940/Explore-logs-2024-12-07.05_11_36.txt)

**Comment by junwei0117** [comment]
We encountered this in alphanet as well, alphanet is running with `v0.7.0-alpha`
[Explore-logs-2024-12-17 18_14_09.txt](https://github.com/user-attachments/files/18164414/Explore-logs-2024-12-17.18_14_09.txt)

**Comment by muXxer** [comment]
@junwei0117 was this all caused on the server with a hardware error? It seems to me that the node crashed at some point and the database in in an inconsistent state. Can you confirm this?

**Comment by junwei0117** [comment]
Just checked our monitoring. in the case of `alphanet`, before the node panic, the network started becoming unstable. the ㄕavg latency of data fetching by our monitoring reached up to 50 seconds.

<img width="839" alt="Image" src="https://github.com/user-attachments/assets/0a30ec62-fa5c-44a6-ae9c-5c6cf6939cbc" />

**Comment by junwei0117** [comment]
In the case of `alphanet`, before the node panic, the latency of data fetching by our monitoring went up to at least 5 seconds.

<img width="920" alt="Image" src="https://github.com/user-attachments/assets/460ee102-4bf5-491a-8a90-bc0e3daa0fd9" />

I also noticed that the outbound request latency for every node rapidly increased, even to 1.3 minutes. there might have been some network issues during the incident

<img width="918" alt="Image" src="https://github.com/user-attachments/assets/f41452cd-4e49-4e6c-bdb0-552ecba18cd1" />

**Comment by junwei0117** [comment]
never encountered the error again, close the issue
